### ISSUE TITLE
uiauto.dev returns HTTP 502

### ISSUE THREAD

**Issue by an-hyeonjun** [codeskyblue/uiautodev#14]
I've been using this UI inspector and worked perfectly as wanted. But, since today, it started not working with HTTP 502 response.
Are you currently shutting down your server for maintenance or something?

**Comment by lushan-sandoval** [comment]
> I've been using this UI inspector and worked perfectly as wanted. But, since today, it started not working with HTTP 502 response. Are you currently shutting down your server for maintenance or something?

I have the same problem

**Comment by dung13796** [comment]
I faced the same issue, i wish it should fix as soon as posible

**Comment by an-hyeonjun** [comment]
FYI: I switched to weditor for temporary resolution. It's not fast as uiauto.dev and has not been maintained, but works. I will stay on weditor until the issue is resolved.

**Comment by ArrayZoneYour** [comment]
You can build from source and use [`https://uiauto.devsleep.com`](https://github.com/codeskyblue/uiautodev/blob/master/uiautodev/common.py#L24) temporarily.

**Comment by codeskyblue** [comment]
Sorry for delay response. Fixed now.
